### ISSUE TITLE
sharness: gateway tests should check headers

### ISSUE THREAD

**Issue by jbenet** [ipfs/kubo#1059]
our sharness gateway tests should check various headers are set correctly, like:

``` yaml
# range requests
Accept-Ranges: bytes

# content
Content-Length: 4
Content-Type: text/plain; charset=utf-8

# caching. for a year on /ipfs -- standard for "forever". more may get ignored :(
Cache-Control: public, max-age=29030400
Last-Modified: Thu, 01 Jan 1970 00:00:01 GMT
Date: Sun, 12 Apr 2015 09:40:07 GMT
Etag: QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6

Suborigin: QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6
X-Ipfs-Path: /ipfs/QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6
```

(on both `GET` and `HEAD` requests. and probably `PUT` too.)
