### ISSUE TITLE
Kubo's Docker image loop crashing with Docker Desktop (WSL2)

### ISSUE THREAD

**Issue by Ghost-chu** [ipfs/kubo#10609]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

docker image

### Version

```Text
It not working at all, but I got version from startup output:

kubo           | ipfs version 0.32.1
```

### Config

```json
It not working at all. So I can't execute any command.
```

### Description

I'm trying bundle the Kubo with my software, so I write a `docker-compose.yml` with these content:

```yaml
services:
  peerbanhelper:
    image: "ghostchu/peerbanhelper-snapshot:sha-1082a88"
    restart: unless-stopped
    container_name: "peerbanhelper"
    volumes:
      - ./:/app/data
    ports:
      - "9898:9898"
    stop_grace_period: 30s
    environment:
      - PBH_KUBO_RPC=/dnsaddr/kubo/tcp/5001
    depends_on:
      - kubo
    links:
      - kubo
  kubo:
    image: "ipfs/kubo:release"
    restart: unless-stopped
    container_name: "kubo"
    ports:
      - "4001:9897"
    stop_grace_period: 30s
    volumes:
      - ./ipfs:/data/ipfs
```

But Kubo seems stuck in crash loop and cannot startup:

```
kubo           | Changing user to ipfs
kubo           | ipfs version 0.32.1
kubo           | generating ED25519 keypair...done
kubo           | peer identity: 12D3KooWKF9fsXzuu792Xx9hvRctBUbFnJsZgY1bmbcSxfQ5voVY
kubo           | initializing IPFS node at /data/ipfs                                                                                                                                                      
kubo           | Error: chmod /data/ipfs/config182763831: operation not permitted                                                                                                                          
kubo exited with code 0
kubo           | ipfs version 0.32.1
kubo           | generating ED25519 keypair...done
kubo           | peer identity: 12D3KooWHECspUCTge45ajGToQL9wtsDdTVYhK4BDeu3nVaJKQyW
kubo           | initializing IPFS node at /data/ipfs                                                                                                                                                      
kubo           | Error: chmod /data/ipfs/config1465488290: operation not permitted
kubo exited with code 0
kubo           | ipfs version 0.32.1
kubo           | generating ED25519 keypair...done                                                                                                                                                         
kubo           | peer identity: 12D3KooWRtDap5jHhcFQvsJt1FiPa2k9bz7btU2uK2mQDH3pr47x
kubo           | initializing IPFS node at /data/ipfs                                                                                                                                                      
kubo           | Error: chmod /data/ipfs/config1361952657: operation not permitted                                                                                                                         
kubo exited with code 1
kubo           | ipfs version 0.32.1                                                                                                                                                                       
kubo           | generating ED25519 keypair...done
kubo           | peer identity: 12D3KooWSF85dr3Z1aS3jvk4NwYYdU87Mev4d95XG5ZEnQ5mMj4P
kubo           | initializing IPFS node at /data/ipfs                                                                                                                                                      
kubo           | Error: chmod /data/ipfs/config2585140927: operation not permitted      
```
I also tried it on Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-118-generic x86_64), it seems working fine, So I think this is an issue with Kubo with Docker Desktop (WSL2).

As additional information, I also provide the version information for Docker Desktop here:

```
Client:
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:03:32 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.32.0 (157355)
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:50 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
