### ISSUE TITLE
node config addresses

### ISSUE THREAD

**Issue by jbenet** [ipfs/kubo#119]
Currently, the config has the local node addresses in two different places (`identity.address` and `rpcaddress`) suggest switching to:

``` yml
addresses:
  net: /ip4/0.0.0.0/tcp/5001
  api: /ip4/127.0.0.1/tcp/4001
```
