### ISSUE TITLE
Adding C:\Windows\Fonts does nothing

### ISSUE THREAD

**Issue by NatoBoram** [ipfs/kubo#7271]
#### Version information:

```yaml
go-ipfs version: 0.6.0-dev
Repo version: 9
System version: amd64/windows
Golang version: go1.14.2
```

#### Description:

The commands `ipfs add -r C:\Windows\Fonts` hangs indefinitely.
